name: Generate Terraform Docs

on:
  #push:
  #branches:
  #- master
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate tf-docs
        uses: terraform-docs/gh-actions@main
        with:
          output-file: README.md
          output-mode: inject
          git-push: true
